[book]
title = "El Lenguaje de Programacion Rust"
author = "Steve Klabnik and Carol Nichols, con Contribuciones de la Comunidad Rust"

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css"]
additional-js = ["ferris.js"]
git-repository-url = "https://github.com/rust-lang/book"
